theme: jekyll-theme-minimal
title: Benjamin MacLellan
logo: "Science Ambassador - Reduced.jpg"
description: "Current M.Sc. student in the field of quantum photonics and optical signal processing"
show_downloads: false
